#!/usr/bin/env python
import socket
import requests
import argparse
import json
import time
import builtwith
import os
Re='\033[1;31m'
Gr='\033[1;32m'
Ye='\033[1;33m'
Blu='\033[1;34m'
Wh='\033[1;37m'
os.system('clear')
print(f'''{Re}


██     ██ ███████ ██████      ███████ ██████  ██    ██ 
██     ██ ██      ██   ██     ██      ██   ██  ██  ██  
██  █  ██ █████   ██████      ███████ ██████    ████   
██ ███ ██ ██      ██   ██          ██ ██         ██    
 ███ ███  ███████ ██████      ███████ ██         ██    
                                                       
                                             Information Gathering Tool             


                                                       
                                                       

''')
parser = argparse.ArgumentParser()
parser.add_argument('-u', help='Target Url')
args = parser.parse_args()
def IP_information(ip):
            print('')
            
            req_api = requests.get(f"http://ipwho.is/{ip}") 
            ip_data = json.loads(req_api.text)
            time.sleep(2)
            print(f"{Wh}\n IP target       :{Gr}", ip)
            print(f"{Wh} Type IP         :{Gr}", ip_data["type"])
            print(f"{Wh} Country         :{Gr}", ip_data["country"])
            print(f"{Wh} Country Code    :{Gr}", ip_data["country_code"])
            print(f"{Wh} City            :{Gr}", ip_data["city"])
            print(f"{Wh} Continent       :{Gr}", ip_data["continent"])
            print(f"{Wh} Continent Code  :{Gr}", ip_data["continent_code"])
            print(f"{Wh} Region          :{Gr}", ip_data["region"])
            print(f"{Wh} Region Code     :{Gr}", ip_data["region_code"])
            print(f"{Wh} Latitude        :{Gr}", ip_data["latitude"])
            print(f"{Wh} Longitude       :{Gr}", ip_data["longitude"])
            a = int(ip_data['latitude'])
            b = int(ip_data['longitude'])
            print(f"{Wh} Maps            :{Gr}",f"https://www.google.com/maps/@{a},{b},8z")
            print(f"{Wh} EU              :{Gr}", ip_data["is_eu"])
            print(f"{Wh} Postal          :{Gr}", ip_data["postal"])
            print(f"{Wh} Calling Code    :{Gr}", ip_data["calling_code"])
            print(f"{Wh} Capital         :{Gr}", ip_data["capital"])
            print(f"{Wh} Borders         :{Gr}", ip_data["borders"])
            print(f"{Wh} Country Flag    :{Gr}", ip_data["flag"]["emoji"])
            print(f"{Wh} ASN             :{Gr}", ip_data["connection"]["asn"])
            print(f"{Wh} ORG             :{Gr}", ip_data["connection"]["org"])
            print(f"{Wh} ISP             :{Gr}", ip_data["connection"]["isp"])
            print(f"{Wh} Domain          :{Gr}", ip_data["connection"]["domain"])
            print(f"{Wh} ID              :{Gr}", ip_data["timezone"]["id"])
            print(f"{Wh} ABBR            :{Gr}", ip_data["timezone"]["abbr"])
            print(f"{Wh} DST             :{Gr}", ip_data["timezone"]["is_dst"])
            print(f"{Wh} Offset          :{Gr}", ip_data["timezone"]["offset"])
            print(f"{Wh} UTC             :{Gr}", ip_data["timezone"]["utc"])
            print(f"{Wh} Current Time    :{Gr}", ip_data["timezone"]["current_time"])

def whois(domain):
 a = {"remoteAddress":domain}
 req = requests.post("https://www.yougetsignal.com/tools/whois-lookup/php/get-whois-lookup-json-data.php",data=a)
 result = req.text.split("<br \/>")
 result = result[1:-1]
 for i in result:
  i = i[2:1000]
  print(f'{Blu}',i)

def technology(target):
 result = builtwith.parse(target)
 for i in result:
  for s in result[i]:
   print(f'{Wh}',i +" : "+ s)
def httpheader(target):
 http = requests.get('https://api.hackertarget.com/httpheaders/?q=' + target).text
 print(f'{Gr}',http)
 
def dns(target):
 result = requests.get('http://api.hackertarget.com/dnslookup/?q=' + target).text
 print(f'{Wh}',result)    
targetip = socket.gethostbyname(args.u)
http = f'https://{args.u}'
print (f'{Ye}IP Information:')
IP_information(targetip)
print(f'{Ye}Whois:')
whois(args.u)
print(f'{Ye}Site Technology Information:')
technology(http)
print(f'{Ye} HTTP Header:')
httpheader(args.u)
print(f'{Ye} DNS Lookup:')
dns(args.u)
